const URL_PATHS_NAMES = {
    LANDING: '',
    FORECAST: 'forecast',
    FAVOURITES: 'favourites'
}

const URL_PARAMS_NAMES = {
    ID: 'id',
    IS_SPECIFIC_LOCATION: 'spec'
}

export const URL_SYMBOLS = {
    SLASH: '/',
    QUESTION_MARK: '?',
    AMPERSAND: '&',
    EQUALS: '=',
    ASTERISK: '*'
}

export const URL_PARAMS = {
    ID: `${URL_SYMBOLS.AMPERSAND}${URL_PARAMS_NAMES.ID}${URL_SYMBOLS.EQUALS}`,
    IS_SPECIFIC_LOCATION: `${URL_SYMBOLS.AMPERSAND}${URL_PARAMS_NAMES.IS_SPECIFIC_LOCATION}${URL_SYMBOLS.EQUALS}`
}

export const URL_PATHS = {
    LANDING: `${URL_SYMBOLS.SLASH}${URL_PATHS_NAMES.LANDING}`,
    FORECAST: `${URL_SYMBOLS.SLASH}${URL_PATHS_NAMES.FORECAST}`,
    FAVOURITES: `${URL_SYMBOLS.SLASH}${URL_PATHS_NAMES.FAVOURITES}`,
    NOT_FOUND: URL_SYMBOLS.ASTERISK
}